doNameSpace("pkgClientEventDefination")

MONSTER_DEAD				= "monster_dead"
PLAYER_HP_CHANGE    		= "player_hp_change"
UPDATE_LEVEL				= "update_level"
UPDATE_GOODS				= "update_goods"
UPDATE_EQUIP				= "update_equip"
UPDATE_WEAR_EQUIP   		= "update_wear_equip"
UPDATE_TAKE_OFF_EQUIP  		= "update_take_off_equip"
UPDATE_LEVEL_UP_EQUIP  		= "update_level_up_equip"
UPDATE_USER_LEVEL	  		= "update_user_level"
UPDATE_ACHIEVEMENT	  		= "update_achievement"
UPDATE_DOWNLOAD	  			= "update_download"
UPDATE_DOWNLOAD_PROCESS 	= "update_download_process"
UPDATE_EXTRACT_PROCESS 	    = "update_extract_process"
EXTRACT_COMPLETE 	   		= "extract_complete"
DOWNLOAD_COMPLETE  			= "download_complete"
ON_HOUSE_LEVEL_UP  			= "on_house_level_up"
ON_HOUSE_UPGRADE  			= "on_house_upgrade"
ON_PLANT_CROP     			= "on_plant_crop"
