_cfg = {}
require("share/config/afk")
require("share/config/effect")
require("share/config/equip")
require("share/config/goods")
require("share/config/goodsReward")
require("share/config/language")
require("share/config/monster")
require("share/config/monsterLib")
require("share/config/test")
require("share/config/level")

require("share/common/json")
require("share/common/log")
require("share/common/math")
require("share/common/public")
require("share/common/table")
require("share/common/type")
require("share/common/class")
require("share/common/random")

require("share/object/user")

require("share/def/database_def")
require("share/def/error_code_def")
require("share/def/event_def")
require("share/def/goods_def")

require("share/tool/nameSpace")
require("share/tool/pkgEventManager")
require("share/tool/pkgTimer")

require("share/const/pkgAFKCfgMgr")
require("share/const/pkgEquipCfgMgr")
require("share/const/pkgGoodsCfgMgr")
require("share/const/pkgLevelCfgMgr")
require("share/const/pkgRewardCfgMgr")