_cfg.goods = {
  [1] = {
   id = 1,
   assetBundle = 'goods',
   name = '金币',
   goodsType = 1,
   isBag = -1,
   extraCfg = '',
  },
  [2] = {
   id = 2,
   assetBundle = 'goods',
   name = '钻石',
   goodsType = 2,
   isBag = -1,
   extraCfg = '',
  },
  [3] = {
   id = 3,
   assetBundle = 'goods',
   name = '经验',
   goodsType = 3,
   isBag = -1,
   extraCfg = '',
  },
  [1004] = {
   id = 1004,
   assetBundle = 'equip_icon',
   name = '裤子',
   goodsType = 1004,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [1005] = {
   id = 1005,
   assetBundle = 'equip_icon',
   name = '鞋子',
   goodsType = 1005,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [1006] = {
   id = 1006,
   assetBundle = 'equip_icon',
   name = '戒指',
   goodsType = 1006,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [1003] = {
   id = 1003,
   assetBundle = 'equip_icon',
   name = '衣服',
   goodsType = 1003,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [100] = {
   id = 100,
   assetBundle = 'goods',
   name = '红糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [101] = {
   id = 101,
   assetBundle = 'goods',
   name = '橙糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [102] = {
   id = 102,
   assetBundle = 'goods',
   name = '黄糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [103] = {
   id = 103,
   assetBundle = 'goods',
   name = '绿糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [104] = {
   id = 104,
   assetBundle = 'goods',
   name = '青糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [105] = {
   id = 105,
   assetBundle = 'goods',
   name = '蓝糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [106] = {
   id = 106,
   assetBundle = 'goods',
   name = '紫糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [107] = {
   id = 107,
   assetBundle = 'goods',
   name = '红宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [108] = {
   id = 108,
   assetBundle = 'goods',
   name = '橙宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [109] = {
   id = 109,
   assetBundle = 'goods',
   name = '黄宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [110] = {
   id = 110,
   assetBundle = 'goods',
   name = '绿宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [111] = {
   id = 111,
   assetBundle = 'goods',
   name = '青宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [112] = {
   id = 112,
   assetBundle = 'goods',
   name = '蓝宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [113] = {
   id = 113,
   assetBundle = 'goods',
   name = '紫宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [1001] = {
   id = 1001,
   assetBundle = 'equip_icon',
   name = '短剑',
   goodsType = 1001,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [1002] = {
   id = 1002,
   assetBundle = 'equip_icon',
   name = '头盔',
   goodsType = 1002,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
}
